
name: Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Python Setup ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          make install
      - name: Lint with Flake8
        run: |
          make lint
      - name: Check Typing
        run: |
          make typing
      - name: Test Package
        run: |
          make test-all